Webinars page
openstax/os-webview pull request #2450
Opened 2023-08-08 21:24 UTC by RoyEJohnson

For: https://github.com/openstax/openstax.org/issues/2274

2023-08-14 17:11 UTC, jivey requested changes
Still working my way through but wanted to get some feedback going

2023-08-14 21:24 UTC, RoyEJohnson commented on src/app/components/explore-by-collection/explore-by-collection.scss
>          .card {
The icons are likely to match better than these examples, but the labels will probably vary between 1 and 2 lines. I've put a min-height on the image container so size differences won't be so dramatic.
![image](https://github.com/openstax/os-webview/assets/7315241/13b61186-cba2-42a2-9e0c-79bb964aad53)

2023-08-14 21:31 UTC, RoyEJohnson commented on src/app/components/paginator/simple-paginator.js
> +            Showing {countMessage} {totalCount} {ofWhat}
This is desired behavior. It's letting them know how many matches and that they are all displayed (as opposed to being paginated).

2023-08-14 22:00 UTC, RoyEJohnson commented on src/app/helpers/use-data.ts
> +        returnValue = (returnValue as Array<unknown>).map(processing.postProcess);
The postProcess step will necessarily be an array operation. The CMS can send other data, but you wouldn't use `postProcess` on it.

2023-08-14 22:05 UTC, RoyEJohnson commented on src/app/helpers/use-data.ts
> +        [promise, options.resolveTo] // eslint-disable-line react-hooks/exhaustive-deps
`options`. To be excruciatingly correct, I'd need to unpack the components of `options` into separate memo'd items and then package them up into another memo.

2023-08-14 23:06 UTC, jivey requested changes
Overall looking good, just a couple issues I noticed with the JS date and alt text

2023-08-15 11:45 UTC, RoyEJohnson commented on src/app/pages/webinars/webinar-cards/latest-webinars.tsx
> +                    <div className='day-of-month'>{data.start.getDay()}</div>
D'oh!

2023-08-15 13:22 UTC, RoyEJohnson commented on src/app/pages/webinars/explore-page/explore-page.tsx
> +                }
I initially tried to write it that way, but I got stymied by TypeScript to the point that I figured it wanted me to separate them out.

2023-08-15 13:35 UTC, jivey approved these changes

2023-08-15 13:46 UTC, merged